# Generated by Django 5.0 on 2024-01-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.CharField(max_length=175)),
                ('is_from_sales_order', models.BooleanField(default=False)),
                ('products', models.ManyToManyField(related_name='production_orders', to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ORDER_RECIEVED', 'ORDER RECIEVED'), ('ORDER_PROCESSING', 'ORDER PROCESSING'), ('INVOICE_ISSUED', 'INVOICE ISSUED')], default='ORDER_RECIEVED', max_length=30)),
                ('customer', models.CharField(max_length=175)),
                ('products', models.ManyToManyField(related_name='sales_orders', to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
