# Generated by Django 5.0 on 2024-01-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
